# PATH: /etc/icinga2/conf.d/hosts.conf

object Host "client-01" {
    
    # defined in: /usr/share/icinga2/include/command-plugins.conf
    check_command = "hostalive"

    # IP and the Endpoint (see t-zones.conf for more)
    address = "10.0.0.2"
    vars.client_endpoint = name
    zone = "z-client-01"

    # OS for os-specific services & host grouping
    vars.os = "Linux"

    # set the group for mail notifications
    # groups & users are defined in /etc/icinga2/conf.d/users.conf
    vars.notification["mail"] = {
        groups = [ "icingaadmins" ]
    }

    # for the two disk services
    vars.disks["disk"] = {
        /* No parameters. */
    }
    vars.disks["disk /"] = {
        disk_partitions = "/"
    }
    
}
