# the check_commands for the services are usually defined here: 
    # /etc/icinga2/conf.d/commands.conf (icinga2)
    # /usr/share/icinga2/include/command-plugins.conf (monitoring-plugins)

# checkcommands cand be tested in bash command line
    # mysql test: /usr/lib/nagios/plugins/check_mysql 
        # then you get an error if something is missing
        # username, port, password and host are missing
        # correct is: /usr/lib/nagios/plugins/check_mysql -p port -u username -p password

# PATH: /etc/icinga2/conf.d/services.conf

apply Service "mysqlserver" {
  
  # defined in /etc/icinga2/conf.d/templates.conf
  import "generic-service"

  # defined in: command-plugins.conf
  check_command = "mysql"

  # variables for the checkcommand
  vars.mysql_hostname = host.address
  vars.mysql_username = host.vars.mysql_username
  vars.mysql_password = host.vars.mysql_password
  vars.mysql_port = host.vars.mysql_port

  # assigned where the mysqlserver attribute is true
  # atrribute should be set to true in the host config
  assign where host.vars.mysqlserver == true

}


# PATH: /etc/icinga2/conf.d/apt.conf

apply Service "apt" {
  
  # defined in /etc/icinga2/conf.d/templates.conf
  import "generic-service" 

  # defined in: command-plugins.conf
  check_command = "apt"

  # to stop getting mails every 30min when there's a package update 
  vars.notificationsinterval = 24h
  
  # normally, the apt service is only for the master node
  # but you can also use it for agent nodes :)
  assign where host.name == NodeName

}